### ISSUE TITLE
TCR sequences import

### ISSUE THREAD

**Issue by vercanie** [IEDB/TCRMatch#17]
Hi @acrinklaw ,

Thanks for developing and maintaining TCRMatch, it's a very useful package!

I'm having one issue - I'm not able to import multiple TCR sequences when using TCRMatch locally. Everything works great for just one sequence. However, when I try to load multiple newline delimited sequences from a txt file, it wouldn't recognize them. The error I'm getting is: " at position 12cid found in ASSLRWGDEQY", where ASSLRWGDEQY is the first sequence in the file and 12 is the first position after its end. I've tried: replacing space/tab/whatever with newline using sed, saving my txt with different encodings, using commas instead of newlines and finally, loading to VDJserver, where I, unfortunately, don't see the TCRMatch option. I'm running it on a cluster (Fedora).

I think it will be something silly that I'm missing and I'll appreciate any help.

Thanks, have a nice day!

Veronika

**Comment by acrinklaw** [comment]
Hey Veronika, that is very strange. Was the file containing the sequences created on Windows by any chance? This has happened a few times since newlines on Windows are actually a carriage return and a newline \r\n. If you'd prefer not to share the sequence file, please first make sure that your sequences are the length you think they should be (length of sequence + 1 for newline) rather than length + 2 for \r\n. If you haven't already, try with sed to replace \r\n with just \n

If this isn't the case, we can debug further. If it is the case, I will open a feature ticket to add the ability to just parse windows + unix newlines.

Thanks
-Austin

**Comment by vercanie** [comment]
YESSS! That was the issue. Thanks so much for the quick and useful reply! Wish all debugging was as easy as this :-)

**Comment by acrinklaw** [comment]
No problem, glad I could help! This has happened a few times so I'll be adding this to a list of features to add. Thanks for using our tool
