### ISSUE TITLE
support for AIRR TSV input

### ISSUE THREAD

**Issue by schristley** [IEDB/TCRMatch#26]
It looks like with the rewrite that AIRR TSV support was lost. I think it should be easy add back, just need to parse the TSV and extract the `junction_aa` column, or maybe `cdr3_aa` because tcrmatch does not want the conserved residues. I suppose the only issue there is `cdr3_aa` is an optional field in AIRR TSV while `junction_aa` is required, so may be better to use `junction_aa` and trim.

I will try to submit a PR.

**Comment by acrinklaw** [comment]
Hey @schristley, I apologize for the oversight. I started a new job and it's been quite a while since I've been actively working on TCRMatch and I just got back to it - I didn't mean to forget our VDJ friends :-)

Your PR looks fantastic and I'll go ahead and merge it after I get a chance to make sure nothing looks strange when I run it on my end - thanks for the help.
