### ISSUE TITLE
empty output 

### ISSUE THREAD

**Issue by alxndravc** [IEDB/TCRMatch#33]
Hi, 

I have been trying to run the TCRMatch tool locally but for some reason it keeps giving me empty output. When I use the exact same input in the online tool it works fine. I noticed that the online tool has a trimming option that is enabled by default. Is this also the case when running the tool locally and if not, is there a way to enable this? 

When I remove the first and last amino acids from all the CDR3 sequences it works but is this a correct approach?

Thanks in advance,

**Comment by wchronister** [comment]
Hi. Yes, the reason you are not getting any matches is because the command-line tool does not currently have the capability to perform sequence trimming, while the web tool does. Apologies for the inconsistency on this feature -- implementing trimming as a command-line option is on our to-do list.

As you mentioned, if you remove the first and last amino acids yourself, you can bypass this problem and the tool should be able to find matches. Our method is to remove the first and last amino acids if (and only if) the first is a C and the last is an F or W; however, in most cases, virtually all CDR3b sequences called by TCR assembly softwares will contain these C...F/W motifs, so simply removing the first and last residues from every sequence (without checking for C...F/W) will suffice.

Thanks for using TCRMatch! Let me know if you run into any other issues.

**Comment by acrinklaw** [comment]
trimming has been addressed with the merge of #35  - closing for now
