### ISSUE TITLE
Score filtering looks inconsistent

### ISSUE THREAD

**Issue by catsutherland** [IEDB/TCRMatch#34]
Hi,

I have a question about the score filtering threshold. I'm finding some CDR3s with a score of 0.97 are making it through the filter and others aren't. For example if I run ASSLIALGDTEAF either online or locally with the default filter of 0.97 then I get no matches. However if I run it online with a filter of 0.90 I get a match with a score of 0.97. Is this something to do with rounding? (I get matches for other CDR3s coming out with a score of 0.97 when I run my files locally so in some cases it does seem to be >= 0.97 not just > 0.97). Related - is there a way to specifiy a lower filter when running locally, not sure if I've missed that somewhere?

Thanks!

**Comment by wchronister** [comment]
Hi, there. Yes, I've checked the sequence you mentioned and I think the issue is rounding -- it looks like there is a match with a score of 0.9675 that is below the 0.97 cutoff, but, when included in the results, gets rounded up and becomes 0.97. We should probably increase the decimal places we use in our output to avoid confusion in situations like this.

When you are running TCRMatch locally, you can use the option "-s [custom cutoff]" in your command to adjust the score threshold (default=0.97) to any value between 0 and 1.

Hope this helps!

--Will

**Comment by catsutherland** [comment]
Hi Will, thanks for clarifying, makes a lot of sense!
