### ISSUE TITLE
output is a 3 column file

### ISSUE THREAD

**Issue by crisjs** [IEDB/TCRMatch#40]
Hi,
When I run the code to generate the initial scores, I get a file with only the first three columns mentioned in the readme. 
Shouldn't I get a file with seven columns? Is there any additional step I should do? I'm running TCRMatch in unbuntu.
Many thanks,
Cristina

**Comment by acrinklaw** [comment]
Hi Cristina,
Are you passing in your own database with -d? Currently the additional annotations for matches is only supported if you are using the default IEDB database. Please post the command you ran, if possible

**Comment by crisjs** [comment]
Hi,
Thank you for your answer. I'm using the default IEDB database and the command:
./tcrmatch -i myinputfile -t num_threads [-s threshold] [-d /path/to/database] [-a] > output_file
TCRMatch version was 0.1.1. I tried also with version 1.0.3 but this one didn't work at all.

**Comment by acrinklaw** [comment]
For version 1.0.3 what exactly happens when you run it? Here is my output running the test sequences:
![image](https://user-images.githubusercontent.com/25108033/225411608-d10224f2-2402-4fc1-bbf7-cc330f27fcfb.png)

I would suggest just running it as
`./tcrmatch -i input.txt -t num_threads > output_file` just to verify that it is working correctly. The other parameters are optional

**Comment by crisjs** [comment]
When I run version 1.0.3, it doesn't do anything, it just says:
_terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted_

With version 0.1.1, I tried the command you suggested (./tcrmatch -i input.txt -t num_threads > output_file), and again, the output file only contains the first three columns.
Can you think of anything else I can try? Thanks

**Comment by crisjs** [comment]
When I run version 1.0.3, it doesn't do anything, it just says:
_terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted_

With version 0.1.1, I tried the command you suggested (./tcrmatch -i input.txt -t num_threads > output_file), and again, the output file only contains the first three columns.
Can you think of anything else I can try? Thanks

**Comment by acrinklaw** [comment]
I believe version 0.1.1 does not support the full output. Can you please copy and paste the exact command you ran? stoi() is only called when parsing the number of threads. An example command would be:
`tcrmatch -i input.txt -t 16 > output.txt`. It sounds like you are passing a string instead of an integer for number of threads? In this case I am specifying 15 as my CPU has 16 cores available. I apologize if the documentation is unclear about this, I will update to make it more apparent

**Comment by crisjs** [comment]
It finally worked! You were right, I wasn't specifying a number for -t.
Thanks so much for your help!
